### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [hooay233/Hoozeeth#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by hooay233** [comment]
OK. I added a screen shot to `Hoozeeth/Hoozeeth.jpg`.Thank you for your support of Hoozeeth!
